print "# generated by usys.pl - do not edit\n";

print "#include \"../src/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("print");
entry("sleep");
entry("pipe");
entry("write");
entry("read");
entry("open");
